import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "boxicons/css/boxicons.min.css";

import { ThemeProvider } from "../components/theme-provider";
import Navbar from "@/app_components/navbar";
import { Separator } from "@/components/ui/separator";
import Breadrumb from "@/app_components/breadrumb";
import * as React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en">
    //   <body className={inter.className}>{children}</body>
    // </html>
    <html lang="en" suppressHydrationWarning>
      <head />
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="dashboard-container ">

            <div className="navbar  border-b">
              <Navbar />
            </div>
            {/* <div className="">
              <Breadrumb  />
            </div>
            */}


            <div className="content p-2">{children}</div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
