quarkus:
  datasource:
    db-kind: postgresql
    username: georgebanin
    password: wonderful143
    jdbc: false
    reactive:
      url: postgresql://localhost:5432/ip_analytics
    quartz:
      db-kind: postgresql
      username: georgebanin
      password: wonderful143
      jdbc:
        url: jdbc:postgresql://localhost:5432/test_quartz

  http:
    cors:
      ~: true
      headers: accept, authorization, content-type, x-requested-with
      methods: GET,PUT,POST
      origins: http://localhost:3000
    port: 8081

  hibernate-orm:
    database:
      default-schema: public
      generation: validate

  config:
    locations: src/main/resources/application.yaml,src/main/resources/quartz-properties.yaml

ping:
  host: localhost
  port: 5432
  db: ip_analytics
  username: georgebanin
  password: wonderful143

kafka:
  bootstrap-servers: 192.168.250.209:9092
  enable-auto-commit: false
  auto-offset-reset: latest
  group-id: ping
  key-serializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
  value-serializer: io.vertx.kafka.client.serialization.JsonObjectDeserializer
  acks: 1




